### ISSUE TITLE
ESP8266 driver background threads dispatching

### ISSUE THREAD

**Issue by maiorfi** [MoleculeDotNet/Molecules#1]
Hi.

As a suggestion, your amazing library could be improved by mean of a ThreadPool utility for background/temporary threads dispatching, primarily in .NETMF, where creating new Thread instances is very expensive (of course, you could also use ThreadPool or TPL your in full .NET library "flavor")

You can take a look at Codeshare on GHI site for a great ThreadPool implementation.

**Comment by martincalsyn** [comment]
Great suggestion - will definitely look into that as I was concerned about the weight of the thread mechanism I used.

**Comment by martincalsyn** [comment]
Code complete, pending testing and checkin

**Comment by martincalsyn** [comment]
fixed and available in nuget and source (https://github.com/DotNetOpenAutomation/serialwifi)
