### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by piwi1263** [MoleculeDotNet/Molecules#4]
Can it made be that the IP Gateway, Subnet mask, DNS, DHCP server is returned as properties ?

**Comment by martincalsyn** [comment]
I have not found an AT command that will return or set this information. I know you can do it in ESP firmware code, but I can't find an AT command. I will leave this issue open for now in case a solution becomes available in the future.

**Comment by piwi1263** [comment]
OK, For the DNS, DHCP I haven't either but for the rest is should be possible

![image](https://cloud.githubusercontent.com/assets/10466039/8359912/a5226e72-1b69-11e5-95bd-6307adae9c03.png)

A nice manual can be found in the ESP SDK -> ...\esp_iot_sdk_v1.0.1\document\EN

If you can not get a hold on it, give me a ping ...

**Comment by martincalsyn** [comment]
Good catch!  I will add that!  Can you send me that link again - it didn't come through. Send it in email please.  Thanks!

**Comment by martincalsyn** [comment]
done
