### ISSUE TITLE
DNS Lookup problem

### ISSUE THREAD

**Issue by piwi1263** [MoleculeDotNet/Molecules#5]
After changing to the new behavior concerning the HttpClient, HttpRequest object and method structure the call to a simple web page returns a DNSLookup failure.

![on20150621 1 - dns lookup fail](https://cloud.githubusercontent.com/assets/10466039/8279011/9653d160-18d0-11e5-87b3-4016c61e2fcd.jpg)

**Comment by piwi1263** [comment]
Using another url I get a different error but the connect seems to be ok.

Consumed: OK
It is now Monday, 22 June 2015 17:32:34

BUFFER CLEARED
Sent command : AT+CIPSTART=0,"TCP","http://www.abbott.com",80
SEND:41 54 2b 43 49 50 53 54   41 52 54 3d 30 2c 22 54   AT+CIPSTART=0,"T
     43 50 22 2c 22 68 74 74   70 3a 2f 2f 77 77 77 2e   CP","http://www.
     61 62 62 6f 74 74 2e 63   6f 6d 22 2c 38 30 0d 0a   abbott.com",80..
RECV:30 2c                                               0,  
RECV:43 4f 4e 4e 45 43 54 0d   0a 0d 0a 4f 4b 0d 0a      CONNECT....OK.. 
Received : 0,CONNECT
Received : OK
Consumed: 0,CONNECT
A first chance exception of type 'System.NullReferenceException' occurred in PervasiveDigital.Net.dll

**Comment by martincalsyn** [comment]
I have not been able to repro this - it may be a local config or network problem.  The null-ref exception can be an expected outcome depending on the stack trace. Can you capture a stack trace next time please?  I'll leave this open until we figure out a root cause.
